#!/usr/bin/env bash
#
# install.sh — install the company-os CLI into ~/.local, self-contained.
#
# The end user needs nothing beyond Python 3.9+ (present on macOS via the
# Command Line Tools and on virtually every Linux). PyYAML — the CLI's only
# third-party dependency — is vendored (pure-Python) and bundled here, so there
# is NO `pip install` and NO network access required.
#
# Layout after install (honours the CLI's own SCRIPT_DIR.parent/"templates"
# assumption by keeping bin/ and templates/ siblings under one share root):
#
#   ~/.local/share/company-os/        <- kit root (bin, templates, skills, …)
#   ~/.local/share/company-os/bin/company-os
#   ~/.local/share/company-os/vendor/yaml/   <- vendored pure-Python PyYAML
#   ~/.local/bin/company-os           <- launcher on your PATH
#
# Override the prefix with:  COMPANY_OS_PREFIX=/some/where ./install.sh
# Uninstall with:            ./install.sh --uninstall
#
set -euo pipefail

# --- resolve source (this script's own directory = the starter kit root) -----
SRC_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# --- destination -------------------------------------------------------------
PREFIX="${COMPANY_OS_PREFIX:-$HOME/.local}"
SHARE_DIR="$PREFIX/share/company-os"
BIN_DIR="$PREFIX/bin"
LAUNCHER="$BIN_DIR/company-os"

say()  { printf '  %s\n' "$*"; }
ok()   { printf '\033[32m✓\033[0m %s\n' "$*"; }
warn() { printf '\033[33m!\033[0m %s\n' "$*"; }
die()  { printf '\033[31m✗\033[0m %s\n' "$*" >&2; exit 1; }

# --- uninstall path ----------------------------------------------------------
if [ "${1:-}" = "--uninstall" ]; then
  printf 'Uninstalling company-os from %s\n' "$PREFIX"
  [ -e "$LAUNCHER" ] && rm -f "$LAUNCHER" && say "removed $LAUNCHER"
  if [ -d "$SHARE_DIR" ]; then rm -rf "$SHARE_DIR" && say "removed $SHARE_DIR"; fi
  ok "Uninstalled."
  exit 0
fi

printf 'Installing company-os → %s\n\n' "$PREFIX"

# --- 1. locate a suitable Python 3.9+ ----------------------------------------
PYTHON=""
for cand in python3 python; do
  if command -v "$cand" >/dev/null 2>&1; then
    if "$cand" -c 'import sys; raise SystemExit(0 if sys.version_info[:2] >= (3, 9) else 1)' 2>/dev/null; then
      PYTHON="$(command -v "$cand")"
      break
    fi
  fi
done
[ -n "$PYTHON" ] || die "Python 3.9+ not found. Install it (e.g. macOS: 'xcode-select --install'; Linux: your package manager), then re-run."
ok "Found Python: $PYTHON ($("$PYTHON" -c 'import platform;print(platform.python_version())'))"

# --- 2. sanity-check the source layout ---------------------------------------
[ -f "$SRC_DIR/bin/company-os" ]   || die "bin/company-os not found next to this script."
[ -d "$SRC_DIR/templates" ]        || die "templates/ not found next to this script."
[ -d "$SRC_DIR/vendor/yaml" ]      || die "vendor/yaml/ (bundled PyYAML) missing — cannot install self-contained."

# --- 3. copy the kit into the share root (preserving bin/+templates/ layout) --
mkdir -p "$SHARE_DIR" "$BIN_DIR"
# Only ship what the CLI needs at runtime plus reference material.
for item in bin templates skills schemas docs vendor README.md; do
  if [ -e "$SRC_DIR/$item" ]; then
    # copy contents fresh; -R preserves the directory shape the CLI expects
    rm -rf "${SHARE_DIR:?}/$item"
    cp -R "$SRC_DIR/$item" "$SHARE_DIR/$item"
  fi
done
# The worked example workspaces live in the source repo (examples/), not the
# shipped kit — the installed CLI scaffolds a fresh workspace via `company-os init`.
chmod +x "$SHARE_DIR/bin/company-os"
ok "Copied kit to $SHARE_DIR"

# --- 4. write the launcher ---------------------------------------------------
# It pins the interpreter, puts the vendored yaml on PYTHONPATH (so `import yaml`
# resolves even when the system has no PyYAML), and execs the REAL CLI file so
# the CLI's own Path(__file__).resolve().parent still points at the kit — which
# is how it finds templates/.
#
# The launcher also self-diagnoses. It is a pointer, not the program: the CLI
# it runs lives under COMPANY_OS_HOME, and this file outlives that tree if the
# kit root is ever removed. `exec` on a missing path yields a bare "no such
# file or directory" naming a path the user never chose and does not recognise,
# which sends people looking for a broken Python install instead of a leftover
# launcher. Say what this file is and how to remove it instead.
cat > "$LAUNCHER" <<LAUNCH
#!/usr/bin/env bash
# company-os launcher (generated by install.sh) — do not edit.
COMPANY_OS_HOME="$SHARE_DIR"

if [ ! -f "\$COMPANY_OS_HOME/bin/company-os" ]; then
  {
    printf 'company-os: stale launcher — the kit it points at is gone.\n\n'
    printf '  missing: %s\n\n' "\$COMPANY_OS_HOME/bin/company-os"
    printf 'This file is a leftover pointer written by the Python kit'"'"'s install.sh.\n'
    printf 'The Python implementation has been replaced by a single static binary.\n\n'
    printf 'Remove the leftovers:\n\n'
    printf '  rm -f  %s\n'  "\$0"
    printf '  rm -rf %s\n\n' "\$COMPANY_OS_HOME"
    printf 'Then install the binary and put it on your PATH. Full procedure:\n'
    printf '  docs/user-guide/how-to/release-and-upgrade.md\n'
    printf '  ("Migrating off the Python kit")\n'
  } >&2
  exit 127
fi

# Prepend vendored pure-Python PyYAML so no pip install is ever required.
export PYTHONPATH="\$COMPANY_OS_HOME/vendor\${PYTHONPATH:+:\$PYTHONPATH}"
exec "$PYTHON" "\$COMPANY_OS_HOME/bin/company-os" "\$@"
LAUNCH
chmod +x "$LAUNCHER"
ok "Installed launcher at $LAUNCHER"

# --- 5. smoke test -----------------------------------------------------------
if "$LAUNCHER" --help >/dev/null 2>&1 || "$LAUNCHER" -h >/dev/null 2>&1; then
  ok "Smoke test passed (company-os runs with the vendored YAML)."
else
  warn "Installed, but 'company-os --help' returned non-zero — run it manually to inspect."
fi

# --- 6. PATH guidance --------------------------------------------------------
printf '\n'
case ":$PATH:" in
  *":$BIN_DIR:"*) ok "$BIN_DIR is already on your PATH." ;;
  *)
    warn "$BIN_DIR is not on your PATH yet. Add this to your shell profile:"
    say  "export PATH=\"$BIN_DIR:\$PATH\""
    say  "(~/.zshrc for zsh, ~/.bashrc for bash — then restart your shell)"
    ;;
esac

printf '\nDone. Try:\n'
say "company-os --help"
say "company-os init my-workspace && cd my-workspace && company-os validate"
