package graph

// CLAUDE.md context nodes: bin/company-os:1592-1801.
//
// Each federation root carries a hand-owned CLAUDE.md with one generated region
// delimited by literal sentinels. The rewrite is FAIL-SAFE: it replaces the
// interior of exactly one balanced marker pair and leaves every byte outside it
// alone, creates the file when it is absent, appends when the file exists
// without markers, and mutates NOTHING when the markers are unbalanced or
// duplicated. Prose that merely mentions the feature can therefore never be
// mistaken for a sentinel — which is why the two patterns are line-anchored.

import (
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"

	"github.com/metuur-ai/uncle-os/company-os-starter/internal/model"
	"github.com/metuur-ai/uncle-os/company-os-starter/internal/workspace"
	"github.com/metuur-ai/uncle-os/company-os-starter/internal/yamlio"
)

const (
	genStart = "<!-- company-os:generated:start — do not edit; " +
		"run `company-os graph build` -->"
	genEnd = "<!-- company-os:generated:end -->"
)

// startRE and endRE are START_RE/END_RE (`:1628-1629`). `(?m)` is Python's
// re.MULTILINE and `.` excludes newlines in both languages, so the anchors mean
// the same thing. The trailing `\s*$` is what eats a file's final newline when
// the end marker is the last line — Python does that too, which is why a
// rewritten node ends without one.
var (
	startRE = regexp.MustCompile(`(?m)^<!--\s*company-os:generated:start.*?-->\s*$`)
	endRE   = regexp.MustCompile(`(?m)^<!--\s*company-os:generated:end.*?-->\s*$`)
)

// RenderGeneratedRegion is render_generated_region (`:1632`).
func RenderGeneratedRegion(block string) string {
	return genStart + "\n" + strings.TrimSpace(block) + "\n" + genEnd
}

// ExtractGeneratedBlock is extract_generated_block (`:1636-1642`): the interior
// of the single balanced marker pair, or ok=false when there is not exactly
// one. Gate 5 uses the same function to decide whether a node is hand-owned.
func ExtractGeneratedBlock(text string) (string, bool) {
	starts := startRE.FindAllStringIndex(text, -1)
	ends := endRE.FindAllStringIndex(text, -1)
	if len(starts) == 1 && len(ends) == 1 && starts[0][0] < ends[0][0] {
		return text[starts[0][1]:ends[0][0]], true
	}
	return "", false
}

// markerImbalance carries the two counts the warn line at `:1664` reports.
type markerImbalance struct{ starts, ends int }

// rewriteGeneratedBlock is rewrite_generated_block (`:1645-1666`). It returns
// whether the file was created or changed, plus the marker counts for the
// unbalanced case — counts rather than a sentence, because nothing below cmd/
// composes human-facing text or writes to stdout (R-2.5, R-2.8).
func rewriteGeneratedBlock(path, block string) (changed bool, bad *markerImbalance, err error) {
	region := RenderGeneratedRegion(block)
	raw, readErr := os.ReadFile(path)
	if os.IsNotExist(readErr) {
		header := fmt.Sprintf("# %s\n\n", filepath.Base(filepath.Dir(path))) +
			"_Hand-owned context. The block below is generated by " +
			"`company-os graph build` — edit outside the markers only._\n\n"
		if err := os.MkdirAll(filepath.Dir(path), 0o777); err != nil {
			return false, nil, model.Errorf(model.ExitArtifact,
				"cannot create %s: %v", filepath.Dir(path), err)
		}
		if err := os.WriteFile(path, []byte(header+region+"\n"), 0o666); err != nil {
			return false, nil, model.Errorf(model.ExitArtifact, "cannot write %s: %v", path, err)
		}
		return true, nil, nil
	}
	if readErr != nil {
		return false, nil, model.Errorf(model.ExitArtifact, "cannot read %s: %v", path, readErr)
	}
	// Path.read_text() applies universal newline translation before the regex
	// runs, and write_text writes back what the translation produced — so a
	// CRLF node is normalized on the first rewrite, under Python too.
	text := readText(raw)

	starts := startRE.FindAllStringIndex(text, -1)
	ends := endRE.FindAllStringIndex(text, -1)
	switch {
	case len(starts) == 0 && len(ends) == 0:
		// Append, altering no prose (R-3.5). The separator normalizes to
		// exactly one blank line between the existing text and the region.
		sep := "\n\n"
		switch {
		case strings.HasSuffix(text, "\n\n"):
			sep = ""
		case strings.HasSuffix(text, "\n"):
			sep = "\n"
		}
		return writeIfChanged(path, text, text+sep+region+"\n")

	case len(starts) == 1 && len(ends) == 1 && starts[0][0] < ends[0][0]:
		// Replace the interior only, verbatim outside (R-3.3).
		return writeIfChanged(path, text, text[:starts[0][0]]+region+text[ends[0][1]:])
	}
	return false, &markerImbalance{starts: len(starts), ends: len(ends)}, nil
}

func writeIfChanged(path, old, updated string) (bool, *markerImbalance, error) {
	if updated == old {
		return false, nil, nil
	}
	if err := os.WriteFile(path, []byte(updated), 0o666); err != nil {
		return false, nil, model.Errorf(model.ExitArtifact, "cannot write %s: %v", path, err)
	}
	return true, nil, nil
}

// readText is Path.read_text(): universal newline translation. Invalid UTF-8
// would raise in Python; nothing here can act on that, and the frontmatter
// parser owns the decision for the documents that carry frontmatter, so a
// CLAUDE.md with a bad byte is repaired to U+FFFD rather than aborting a build
// that touches a dozen other roots.
func readText(raw []byte) string {
	s := strings.ReplaceAll(string(raw), "\r\n", "\n")
	return strings.ReplaceAll(s, "\r", "\n")
}

// NodeRoots is node_roots (`:1669-1675`): the federation roots that carry a
// CLAUDE.md context node.
//
// knowledge/ is included and is the reason this list is not graphRoots(): the
// catalog root is navigable even though its contents are never ingested as
// graph documents. Indexed, not governed.
func NodeRoots(ws *workspace.Workspace) []string {
	roots := []string{ws.Company}
	roots = append(roots, ws.AllPlatforms()...)
	roots = append(roots, ws.AllTeams()...)
	roots = append(roots,
		filepath.Join(ws.Root, "company-ontology"),
		filepath.Join(ws.Root, workspace.KnowledgeRoot))
	out := roots[:0]
	for _, r := range roots {
		if exists(r) {
			out = append(out, r)
		}
	}
	return out
}

// knowledgeDoc is one (path, title) pair from iter_knowledge_docs.
type knowledgeDoc struct{ Rel, Title string }

// iterKnowledgeDocs is iter_knowledge_docs (`:1678-1700`). Deliberately
// tolerant, unlike IterGraphDocs: no frontmatter is required and nothing is
// written back. Knowledge slices are foreign, read-only content.
//
// Note the scratchpad test is on the WORKSPACE-RELATIVE parts here, where
// IterGraphDocs tests the absolute ones. That asymmetry is in the oracle, with
// a comment explaining it, and both halves are reproduced as they are.
func iterKnowledgeDocs(ws *workspace.Workspace) ([]knowledgeDoc, error) {
	root := filepath.Join(ws.Root, workspace.KnowledgeRoot)
	if !isDir(root) {
		return nil, nil
	}
	mds, err := rglobMarkdown(root)
	if err != nil {
		return nil, err
	}
	var out []knowledgeDoc
	for _, md := range mds {
		rel, ok := under(root, md)
		if !ok {
			continue
		}
		if hasPathComponent(rel, "scratchpad") || filepath.Base(md) == "CLAUDE.md" {
			continue
		}
		title := strings.TrimSuffix(filepath.Base(md), filepath.Ext(md))
		if raw, err := os.ReadFile(md); err == nil {
			for _, line := range strings.Split(readText(raw), "\n") {
				if strings.HasPrefix(line, "# ") {
					if t := strings.TrimSpace(line[2:]); t != "" {
						title = t
					}
					break
				}
			}
		}
		out = append(out, knowledgeDoc{Rel: rel, Title: title})
	}
	return out, nil
}

// RootTeamMeta is root_team_meta (`:1703-1707`): the team.yaml mapping for a
// team root, and nil for every other root. The nil/non-nil distinction is what
// tells BuildClaudeNode and gate 5 whether an identity block applies at all —
// a team with no identity keys still gets an empty mapping, not nil.
func RootTeamMeta(ws *workspace.Workspace, root string) yamlio.PyMap {
	if filepath.Base(filepath.Dir(root)) != "teams" {
		return nil
	}
	m, err := loadMapping(filepath.Join(root, "team.yaml"))
	if err != nil || m == nil {
		// `m if isinstance(m, dict) else {}` — a team.yaml holding a list is
		// treated as having no identity blocks, not as a failure.
		return yamlio.PyMap{}
	}
	return m
}

// RootDoc is one entry of a root's document group: the path relative to that
// root, plus its frontmatter.
type RootDoc struct {
	Rel  string
	Meta yamlio.PyMap
}

// GroupDocsByRoot is group_docs_by_root (`:1710-1722`), keyed by root path.
//
// Each document is assigned to the FIRST root that contains it and to no other,
// which is what keeps a platform's docs out of the company root's index. The
// per-root sort is by the relative path as a STRING — `sorted(v, key=x[0])` on
// a str — not the PurePath order the walk used to find them. The two orders
// differ, and this is the one that reaches the rendered index.
func GroupDocsByRoot(ws *workspace.Workspace, docs []Doc) map[string][]RootDoc {
	roots := NodeRoots(ws)
	groups := make(map[string][]RootDoc, len(roots))
	for _, r := range roots {
		groups[r] = nil
	}
	for _, d := range docs {
		for _, r := range roots {
			rel, ok := under(r, d.Path)
			if !ok {
				continue
			}
			groups[r] = append(groups[r], RootDoc{Rel: rel, Meta: d.Meta})
			break
		}
	}
	for r := range groups {
		v := groups[r]
		sort.SliceStable(v, func(i, j int) bool { return v[i].Rel < v[j].Rel })
	}
	return groups
}

// BuildClaudeNode is build_claude_node (`:1725-1774`): a pure render of one
// root's generated block — a doc index grouped by `type`, links to the sibling
// federation roots, and, for a team root, an identity summary. No timestamp and
// no walk-order dependence anywhere in it, which is what makes the rewrite
// idempotent (R-3.7).
func BuildClaudeNode(ws *workspace.Workspace, root string, docs []RootDoc,
	teamMeta yamlio.PyMap, hasTeamMeta bool) (string, error) {

	name := filepath.Base(root)
	lines := []string{"## " + name + " — context index", ""}

	if name == workspace.KnowledgeRoot {
		// `docs` is empty here by construction — IterGraphDocs never walks the
		// catalog root — so the foreign slices are indexed tolerantly instead,
		// grouped by the directory each landed in.
		kdocs, err := iterKnowledgeDocs(ws)
		if err != nil {
			return "", err
		}
		areas := map[string][]knowledgeDoc{}
		var areaNames []string
		for _, kd := range kdocs {
			area := path0(kd.Rel)
			if _, seen := areas[area]; !seen {
				areaNames = append(areaNames, area)
			}
			areas[area] = append(areas[area], kd)
		}
		if len(areaNames) > 0 {
			sort.Strings(areaNames)
			lines = append(lines, "### Knowledge areas")
			for _, area := range areaNames {
				lines = append(lines, "- **"+area+"**")
				group := areas[area]
				sort.SliceStable(group, func(i, j int) bool {
					if group[i].Rel != group[j].Rel {
						return group[i].Rel < group[j].Rel
					}
					return group[i].Title < group[j].Title
				})
				for _, kd := range group {
					lines = append(lines, "  - ["+kd.Title+"]("+kd.Rel+")")
				}
			}
			lines = append(lines, "")
		}
	} else {
		byType := map[string][]RootDoc{}
		var types []string
		for _, d := range docs {
			t := "other"
			if v := d.Meta.Get("type"); !yamlio.PyFalsy(v) {
				t = yamlio.PyString(v)
			}
			if _, seen := byType[t]; !seen {
				types = append(types, t)
			}
			byType[t] = append(byType[t], d)
		}
		if len(types) > 0 {
			sort.Strings(types)
			lines = append(lines, "### Doc index")
			for _, t := range types {
				lines = append(lines, "- **"+t+"**")
				group := byType[t]
				sort.SliceStable(group, func(i, j int) bool { return group[i].Rel < group[j].Rel })
				for _, d := range group {
					// `meta.get("title") or meta.get("id") or Path(rel).name`
					title := filepath.Base(d.Rel)
					if v := d.Meta.Get("id"); !yamlio.PyFalsy(v) {
						title = yamlio.PyString(v)
					}
					if v := d.Meta.Get("title"); !yamlio.PyFalsy(v) {
						title = yamlio.PyString(v)
					}
					lines = append(lines, "  - ["+title+"]("+d.Rel+")")
				}
			}
			lines = append(lines, "")
		}
	}

	var others []string
	for _, r := range NodeRoots(ws) {
		if r != root {
			others = append(others, r)
		}
	}
	if len(others) > 0 {
		lines = append(lines, "### Federation roots")
		for _, r := range others {
			// POSIX separators so the committed block is byte-identical across
			// operating systems — idempotency has to survive a Windows checkout.
			link, err := filepath.Rel(root, filepath.Join(r, "CLAUDE.md"))
			if err != nil {
				return "", model.Errorf(model.ExitArtifact,
					"cannot relate %s to %s: %v", r, root, err)
			}
			lines = append(lines, "- ["+filepath.Base(r)+"]("+filepath.ToSlash(link)+")")
		}
		lines = append(lines, "")
	}

	if hasTeamMeta {
		if summary := IdentitySummary(teamMeta); len(summary) > 0 {
			lines = append(lines, "### Team identity")
			lines = append(lines, summary...)
			lines = append(lines, "")
		}
	}
	return strings.TrimSpace(strings.Join(lines, "\n")), nil
}

// path0 is `Path(rel).parent.as_posix()` collapsed to the "." sentinel the
// oracle uses for a doc sitting directly under knowledge/.
func path0(rel string) string {
	parent := filepath.ToSlash(filepath.Dir(rel))
	if parent == "." || parent == "" {
		return "."
	}
	return parent
}

// IdentitySummary is identity_summary (`:1568-1589`): the markdown lines
// summarizing a team's roster, channels and pointers. A pure function of
// team.yaml, empty when no identity block is present. Malformed rows are
// skipped rather than reported — the reporting is gate 5's job.
func IdentitySummary(teamMeta yamlio.PyMap) []string {
	var lines []string
	if people := mappings(teamMeta.Get("roster")); len(people) > 0 {
		parts := make([]string, 0, len(people))
		for _, r := range people {
			parts = append(parts, fmt.Sprintf("%s (%s)",
				strOrNone(r.Get("name")), strOrNone(r.Get("role"))))
		}
		lines = append(lines, "**Roster:** "+strings.Join(parts, ", "))
	}
	if chans := mappings(teamMeta.Get("channels")); len(chans) > 0 {
		parts := make([]string, 0, len(chans))
		for _, c := range chans {
			if v := c.Get("system"); !yamlio.PyFalsy(v) {
				parts = append(parts, fmt.Sprintf("%s (%s)",
					strOrNone(c.Get("name")), yamlio.PyString(v)))
				continue
			}
			parts = append(parts, strOrNone(c.Get("name")))
		}
		lines = append(lines, "**Channels:** "+strings.Join(parts, ", "))
	}
	if ptrs := mappings(teamMeta.Get("pointers")); len(ptrs) > 0 {
		parts := make([]string, 0, len(ptrs))
		for _, p := range ptrs {
			target := p.Get("url")
			if yamlio.PyFalsy(target) {
				target = p.Get("id")
			}
			parts = append(parts, fmt.Sprintf("[%s](%s)",
				strOrNone(p.Get("label")), strOrNone(target)))
		}
		lines = append(lines, "**Pointers:** "+strings.Join(parts, ", "))
	}
	return lines
}

// mappings is `[x for x in (value or []) if isinstance(x, dict)]`.
func mappings(v yamlio.PyValue) []yamlio.PyMap {
	list, ok := v.(yamlio.PySeq)
	if !ok {
		return nil
	}
	var out []yamlio.PyMap
	for _, item := range list {
		if m, ok := item.(yamlio.PyMap); ok {
			out = append(out, m)
		}
	}
	return out
}

// strOrNone is the f-string interpolation of a `.get()`: an absent key renders
// as the literal "None", because Python interpolates the None it returned.
func strOrNone(v yamlio.PyValue) string {
	if v == nil {
		return "None"
	}
	return yamlio.PyString(v)
}

// writeClaudeNodes is write_claude_nodes (`:1777-1784`).
//
// The findings come back as ONE ordered slice rather than as separate written
// and skipped lists: Python's warn() prints where it happens, so an unbalanced
// root's warning lands between the two neighbouring "node …" lines, and
// bucketing by severity would move it.
func writeClaudeNodes(ws *workspace.Workspace, docs []Doc) ([]model.Finding, error) {
	groups := GroupDocsByRoot(ws, docs)
	var out []model.Finding
	for _, root := range NodeRoots(ws) {
		teamMeta := RootTeamMeta(ws, root)
		block, err := BuildClaudeNode(ws, root, groups[root], teamMeta, teamMeta != nil)
		if err != nil {
			return nil, err
		}
		node := filepath.Join(root, "CLAUDE.md")
		changed, unbalanced, err := rewriteGeneratedBlock(node, block)
		if err != nil {
			return nil, err
		}
		if unbalanced != nil {
			out = append(out, model.Finding{
				Severity: model.SevWarn,
				Code:     model.CodeGraphNodeMarkersUnbalanced,
				// The warn line names the ABSOLUTE path, not the
				// workspace-relative one every neighbouring line uses: warn()
				// interpolates the Path it was handed (`:1665`).
				Path: node,
				Fields: model.Fields{
					"path": node, "starts": unbalanced.starts, "ends": unbalanced.ends,
				},
			})
		}
		if changed {
			rel := relTo(ws.Root, node)
			out = append(out, model.Finding{
				Severity: model.SevOK,
				Code:     model.CodeGraphNodeWritten,
				Path:     rel,
				Fields:   model.Fields{"path": rel},
			})
		}
	}
	return out, nil
}
