package main

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/metuur-ai/uncle-os/company-os-starter/internal/graph"
	"github.com/metuur-ai/uncle-os/company-os-starter/internal/model"
	"github.com/metuur-ai/uncle-os/company-os-starter/internal/scaffold"
	"github.com/metuur-ai/uncle-os/company-os-starter/internal/tui"
	"github.com/metuur-ai/uncle-os/company-os-starter/internal/workspace"
)

// The advisor: derived artifacts that are missing or stale, and the command that
// fixes each (R-5.18 – R-5.22).
//
// It exists because each of these is already reported somewhere the reader has
// to be looking already: an unresolved effective-governance.yaml is a [warn]
// line inside `today --role`, and a drifted generated block is a [FAIL] line at
// the end of `validate`. Both name their fix; neither is seen by someone who
// has not yet learned which command to run.
//
// A fresh `init` leaves a drifted block behind in one real case: when the
// workspace's ABSOLUTE path contains a directory named `scratchpad`, tags.go
// skips every document, `graph build` derives a node from nothing, and gate
// [5/7] reports drift. Elsewhere `init` then `validate` exits 0. Both halves of
// that sentence were got wrong in turn — see task 6.11 for the sequence and
// 6.12 for the open decision.
//
// The fresh-workspace case a user hits at ANY path is the second diagnosis
// below: `init` writes no teams/<t>/generated/, so governance is unresolved
// until `governance resolve` runs.
//
// Every offer is a real invocation routed through the existing Form/Action path,
// so the guarantees are the ones already proved: the preview is flag-complete
// and derived (R-5.6, R-5.7), and nothing is written before the confirmation
// (R-5.8). An offer this package could not express as an *Args is an offer it
// does not make.

// diagnosis is one detected problem. Fix is nil when the problem is real but has
// no command that can safely resolve it — those are shown and explained, never
// offered, because a button that writes a guess is worse than a sentence.
type diagnosis struct {
	Title  string
	Detail string
	Fix    *Args
}

// advise inspects a workspace and returns what is wrong with it, in the order a
// reader should deal with it: derived state first, because `graph build` is
// cheap and clears the most common failure, then per-team gaps.
func advise(ws *workspace.Workspace, root string) []diagnosis {
	var out []diagnosis

	// 1. Generated context blocks. NodeGate is the same check `validate` runs,
	//    so the advisor cannot disagree with the gate about whether this is a
	//    problem.
	if g, err := graph.NodeGate(ws, 5); err == nil {
		var drifted []string
		for _, f := range g.Findings {
			if f.Severity == model.SevFail {
				drifted = append(drifted, f.Subject)
			}
		}
		if len(drifted) > 0 {
			out = append(out, diagnosis{
				Title: fmt.Sprintf("fix %d drifted generated block(s)", len(drifted)),
				Detail: "These files carry a company-os:generated block that no longer\n" +
					"matches what the workspace would produce:\n\n  " +
					strings.Join(drifted, "\n  ") +
					"\n\n`graph build` is idempotent — running it when nothing has\n" +
					"drifted changes nothing.\n\n" +
					"If this is a workspace you just created, check whether its path\n" +
					"contains a directory named `scratchpad`: documents under one are\n" +
					"skipped when tags are derived, so the block is built from nothing\n" +
					"and `graph build` will not settle it.",
				Fix: &Args{Root: root, Cmd: "graph", Action: "build"},
			})
		}
	}

	// 1b. Feature indexes — validate's OTHER derived-artifact gate. Missing here
	//     until 2026-07-27, which made R-5.18's "each derived artifact" false:
	//     the advisor covered gate 5 and silently ignored gate 6. Found in review
	//     by @uncle-dev:uncle-po.
	//
	//     Its two failing codes need opposite treatment, which is why this is not
	//     folded into the loop above. Drift is derived state and `graph build`
	//     settles it. An unresolved reference is an AUTHORING error — a component
	//     the index points at that does not resolve — and rebuilding cannot fix
	//     it, so it is explained and not offered (R-5.22). Absent is SevOK: the
	//     gate is absence-tolerant and so is this.
	if g, err := graph.FeatureIndexGate(ws, 6); err == nil {
		var drifted, unresolved []string
		for _, f := range g.Findings {
			if f.Severity != model.SevFail {
				continue
			}
			switch f.Code {
			case model.CodeFeatureIndexDrift:
				drifted = append(drifted, f.Subject)
			case model.CodeFeatureIndexUnresolved:
				unresolved = append(unresolved, f.Subject)
			}
		}
		if len(drifted) > 0 {
			out = append(out, diagnosis{
				Title: fmt.Sprintf("rebuild %d drifted feature index(es)", len(drifted)),
				Detail: "The derived component->artifact map is stale for:\n\n  " +
					strings.Join(drifted, "\n  ") +
					"\n\nIt is regenerated by the same command that rebuilds context\n" +
					"blocks, so one `graph build` settles both.",
				Fix: &Args{Root: root, Cmd: "graph", Action: "build"},
			})
		}
		if len(unresolved) > 0 {
			out = append(out, diagnosis{
				Title: fmt.Sprintf("unresolved reference in %d feature index(es) (no fix offered)",
					len(unresolved)),
				Detail: "These platforms have a feature index pointing at something\n" +
					"that does not resolve:\n\n  " +
					strings.Join(unresolved, "\n  ") +
					"\n\nNo fix is offered: rebuilding derives the same broken reference\n" +
					"again, because the index is correct about what the artifacts say.\n" +
					"The component id or the artifact referencing it has to be edited.\n" +
					"Run `company-os validate` for the specific reference.",
			})
		}
	}

	// AllTeams returns DIRECTORIES, not ids. Using the path as a team id builds
	// invocations like `--team /abs/path/teams/core`, which parse but address
	// nothing — baseNames is what the rest of the catalog already does.
	for _, team := range baseNames(ws.AllTeams()) {
		tdir := filepath.Join(ws.Teams, team)

		// 2. Resolved governance. `today` warns about this; the warning names
		//    the command but the reader has to be running `today` to see it.
		eff := filepath.Join(tdir, "generated", "effective-governance.yaml")
		if _, err := os.Stat(eff); err != nil {
			out = append(out, diagnosis{
				Title: "resolve governance for team " + team,
				Detail: "teams/" + team + "/generated/effective-governance.yaml does not\n" +
					"exist. It is derived from the company baseline, the platform\n" +
					"requirements, and this team's deviations — nothing reads the\n" +
					"team's effective rules until it is generated.",
				Fix: &Args{Root: root, Cmd: "governance", Action: "resolve", Team: team},
			})
		}

		// 3. Scaffolded team files. Detected from the same definition the repair
		//    writes from, so the count shown is the count that will be created.
		if missing, err := scaffold.MissingTeamFiles(ws, team); err == nil && len(missing) > 0 {
			out = append(out, diagnosis{
				Title: fmt.Sprintf("restore %d missing file(s) for team %s", len(missing), team),
				Detail: "These files belong to a scaffolded team and are absent:\n\n  " +
					strings.Join(missing, "\n  ") +
					"\n\n--repair writes only what is missing and never touches a file\n" +
					"that exists, so an edited definition-of-done is safe.",
				Fix: &Args{Root: root, Cmd: "add", Kind: "team", Name: team, Repair: true},
			})
		}
	}

	// 4. Federation manifest. Detected, explained, NOT offered: a manifest needs
	//    repo URLs and commit pins that nothing here can guess, and a form that
	//    produced a plausible-but-wrong manifest would be worse than the missing
	//    file. Only surfaced when the workspace looks federated already, so a
	//    plain monorepo is not nagged about a feature it does not use.
	if _, err := os.Stat(filepath.Join(ws.Root, workspace.ManifestName)); err != nil {
		if _, lockErr := os.Stat(filepath.Join(ws.Root, "workspace.lock.yaml")); lockErr == nil {
			out = append(out, diagnosis{
				Title: "missing " + workspace.ManifestName + " (no fix offered)",
				Detail: "This workspace has a workspace.lock.yaml but no " +
					workspace.ManifestName + ".\nThe lock records what was synced; the manifest " +
					"records what SHOULD be\nsynced, and only the manifest can be authored.\n\n" +
					"No fix is offered here on purpose: a manifest needs repo URLs and\n" +
					"commit pins that nothing can infer. Restore it from version control,\n" +
					"or write it following docs/FEDERATION-RUNBOOK.md.",
			})
		}
	}
	return out
}

// adviceScreens turns diagnoses into screens.
//
// A diagnosis WITH a fix becomes a field-less form: opening it goes straight to
// the previewed invocation, and `y` runs it. A diagnosis without one is a plain
// body — readable, and incapable of writing anything.
func adviceScreens(ws *workspace.Workspace, root string) []tui.Screen {
	var screens []tui.Screen
	for _, d := range advise(ws, root) {
		d := d
		if d.Fix == nil {
			screens = append(screens, tui.Screen{
				Title: d.Title,
				Run:   func(string) (string, error) { return d.Detail + "\n", nil },
			})
			continue
		}
		screens = append(screens, tui.Screen{
			Title: d.Title,
			Form: &tui.Form{
				Build: func([]string) (tui.Action, error) {
					return &invocation{ws: ws, args: d.Fix}, nil
				},
			},
		})
	}
	return screens
}
