package yamlio

import (
	"encoding/json"
	"os"
	"testing"

	"gopkg.in/yaml.v3"
)

// truthRow is one measured row of testdata/pyyaml-truth.json. That file is
// generated by loading a scalar corpus through the repo's vendored PyYAML
// 6.0.2 and through gopkg.in/yaml.v3 v3.0.1 and recording what each produced.
// Nothing in it is hand-written, so the expectations below are measurements
// rather than recollections.
type truthRow struct {
	Form   string `json:"form"`
	Expect string `json:"expect"`
	PyTag  string `json:"pyTag"`
	PyType string `json:"pyType"`
	PyStr  string `json:"pyStr"`
	GoTag  string `json:"goTag"`
	GoStr  string `json:"goStr"`
	// Diverges records that yaml.v3's own rendering differs from PyYAML's.
	// These are the rows that make this package necessary.
	Diverges bool `json:"diverges"`
}

func loadTruth(t *testing.T) []truthRow {
	t.Helper()
	blob, err := os.ReadFile("testdata/pyyaml-truth.json")
	if err != nil {
		t.Fatalf("read truth table: %v", err)
	}
	var rows []truthRow
	if err := json.Unmarshal(blob, &rows); err != nil {
		t.Fatalf("parse truth table: %v", err)
	}
	if len(rows) == 0 {
		t.Fatal("truth table is empty")
	}
	return rows
}

// scalarNode parses "k: <form>" and hands back the value node, which is how
// every scalar in the workspace actually reaches the resolver.
func scalarNode(t *testing.T, form string) (*yaml.Node, error) {
	t.Helper()
	src := form
	if form == "<EMPTY>" {
		src = ""
	}
	var doc yaml.Node
	if err := yaml.Unmarshal([]byte("k: "+src+"\n"), &doc); err != nil {
		return nil, err
	}
	return doc.Content[0].Content[1], nil
}

// TestResolveMatchesPyYAML asserts that for every measured form, the resolved
// kind matches PyYAML's tag and the rendering matches Python's str().
func TestResolveMatchesPyYAML(t *testing.T) {
	for _, row := range loadTruth(t) {
		t.Run(row.Form, func(t *testing.T) {
			node, err := scalarNode(t, row.Form)
			if row.Expect == "parse_error" {
				if err == nil {
					t.Fatalf("want a parse error (PyYAML: %s), got node %q", row.PyStr, node.Value)
				}
				return
			}
			if err != nil {
				t.Fatalf("parse %q: %v", row.Form, err)
			}

			got, err := Resolve(node)
			if row.Expect == "resolve_error" {
				if err == nil {
					t.Fatalf("want a resolve error (PyYAML: %s), got %q", row.PyStr, got.String())
				}
				return
			}
			if err != nil {
				t.Fatalf("Resolve(%q): %v", row.Form, err)
			}

			if got.Kind.Tag() != row.PyTag {
				t.Errorf("kind: got %s, PyYAML resolves %s", got.Kind.Tag(), row.PyTag)
			}
			// The merge and value tags resolve but have no Python value, so
			// only the tag is checked for them.
			if row.Expect == "construct_error" {
				return
			}
			if s := got.String(); s != row.PyStr {
				t.Errorf("render: got %q, PyYAML str() gives %q (yaml.v3 alone gives %q)",
					s, row.PyStr, row.GoStr)
			}
		})
	}
}

// TestDivergentFormsAreCovered guards the table itself: if a regeneration ever
// produced a corpus where nothing diverges, the suite above would pass while
// proving nothing.
func TestDivergentFormsAreCovered(t *testing.T) {
	rows := loadTruth(t)
	var divergent int
	for _, row := range rows {
		if row.Diverges {
			divergent++
		}
	}
	if divergent == 0 {
		t.Fatal("no divergent forms in the truth table; the table is not exercising the port risk")
	}
	t.Logf("%d of %d measured forms render differently under yaml.v3 alone", divergent, len(rows))
}

// TestQuotedAndUnquotedShareOnePath is R-1.6's named case: line 8 of the
// deviations fixture is unquoted and line 10 is quoted, and both must come out
// as the same rendered date string.
func TestQuotedAndUnquotedShareOnePath(t *testing.T) {
	const src = "reviewDate: 2035-01-15\nother: '2035-01-14'\n"
	var doc yaml.Node
	if err := yaml.Unmarshal([]byte(src), &doc); err != nil {
		t.Fatalf("parse: %v", err)
	}
	m := doc.Content[0]

	unquoted, err := Resolve(m.Content[1])
	if err != nil {
		t.Fatalf("unquoted: %v", err)
	}
	quoted, err := Resolve(m.Content[3])
	if err != nil {
		t.Fatalf("quoted: %v", err)
	}

	if unquoted.Kind != KindTimestamp {
		t.Errorf("unquoted kind: got %s, want !!timestamp", unquoted.Kind.Tag())
	}
	if quoted.Kind != KindStr {
		t.Errorf("quoted kind: got %s, want !!str", quoted.Kind.Tag())
	}
	if got := unquoted.String(); got != "2035-01-15" {
		t.Errorf("unquoted render: got %q, want %q", got, "2035-01-15")
	}
	if got := quoted.String(); got != "2035-01-14" {
		t.Errorf("quoted render: got %q, want %q", got, "2035-01-14")
	}
}

// TestGitCommitPinKeepsPrecision covers the divergence found in the committed
// fixtures: an unquoted all-digit 40-character commit SHA. PyYAML's int is
// arbitrary precision and renders every digit; yaml.v3 overflows int64, falls
// back to float64, and renders 1.1111111111111112e+39 — a silently corrupted
// git ref.
func TestGitCommitPinKeepsPrecision(t *testing.T) {
	const sha = "1111111111111111111111111111111111111111"
	var doc yaml.Node
	if err := yaml.Unmarshal([]byte("pin: {commit: "+sha+"}\n"), &doc); err != nil {
		t.Fatalf("parse: %v", err)
	}
	node := doc.Content[0].Content[1].Content[1]

	got, err := Resolve(node)
	if err != nil {
		t.Fatalf("Resolve: %v", err)
	}
	if got.Kind != KindInt {
		t.Fatalf("kind: got %s, want !!int", got.Kind.Tag())
	}
	if got.String() != sha {
		t.Errorf("render: got %q, want %q", got.String(), sha)
	}
}

// TestExplicitTagsDispatchOnTheTag covers the R-1.7a hole: PyYAML runs
// resolution and construction as separate passes, and an explicit tag suppresses
// only the first. Treating a tagged scalar as a string made `!!int 0` a
// non-empty string — truthy — where Python has an int 0 that `or {}` collapses.
//
// Every PyStr below is str(safe_load("a: <form>")['a']) under the vendored
// PyYAML 6.0.2.
func TestExplicitTagsDispatchOnTheTag(t *testing.T) {
	cases := []struct {
		form  string
		kind  Kind
		pyStr string
		falsy bool
	}{
		{"!!int 0", KindInt, "0", true},
		{"!!int 7", KindInt, "7", false},
		{"!!int '0'", KindInt, "0", true},    // the tag outranks the quoting
		{`!!int "12"`, KindInt, "12", false}, // ...and the double quoting too
		{"!!int 0x10", KindInt, "16", false},
		{"!!int 010", KindInt, "8", false},
		{"!!int 0o17", KindInt, "15", false},
		{"!!int 1_000", KindInt, "1000", false},
		{"!!int -0x10", KindInt, "-16", false},
		{"!!int 1:30", KindInt, "90", false},
		{"!!float 0", KindFloat, "0.0", true},
		{"!!float 12", KindFloat, "12.0", false}, // reFloat does not match "12"
		{"!!float 1.5", KindFloat, "1.5", false},
		{"!!float '2.5'", KindFloat, "2.5", false},
		{"!!float 1:30", KindFloat, "90.0", false},
		{"!!float .inf", KindFloat, "inf", false},
		{"!!float -.inf", KindFloat, "-inf", false},
		{"!!bool false", KindBool, "False", true},
		{"!!bool no", KindBool, "False", true},
		{"!!bool 'yes'", KindBool, "True", false},
		{"!!null ''", KindNull, "None", true},
		{"!!null ~", KindNull, "None", true},
		{"!!null null", KindNull, "None", true},
		{"!!str 0", KindStr, "0", false},
		{"!!str ''", KindStr, "", true},
		{"!!str 2035-01-15", KindStr, "2035-01-15", false},
		{"!!timestamp 2035-01-15", KindTimestamp, "2035-01-15", false},
		{"!!timestamp '2035-01-15 10:00:00'", KindTimestamp, "2035-01-15 10:00:00", false},
	}
	for _, tc := range cases {
		t.Run(tc.form, func(t *testing.T) {
			node, err := scalarNode(t, tc.form)
			if err != nil {
				t.Fatalf("parse: %v", err)
			}
			got, err := Resolve(node)
			if err != nil {
				t.Fatalf("Resolve: %v", err)
			}
			if got.Kind != tc.kind {
				t.Errorf("kind: got %s, PyYAML constructs %s", got.Kind.Tag(), tc.kind.Tag())
			}
			if s := got.String(); s != tc.pyStr {
				t.Errorf("render: got %q, PyYAML str() gives %q", s, tc.pyStr)
			}
			// The whole point: `or {}` branches on this, so a wrong kind is a
			// wrong control-flow decision, not a cosmetic one.
			if isFalsy(node) != tc.falsy {
				t.Errorf("falsy: got %v, Python's bool() says falsy=%v", isFalsy(node), tc.falsy)
			}
		})
	}

	// Forms whose tag names a constructor that then refuses the text. PyYAML
	// raises ValueError, KeyError, IndexError or AttributeError on each; without
	// dispatching on the tag these were all silently accepted as strings.
	for _, form := range []string{
		"!!int abc", "!!int ''", "!!bool maybe", "!!bool ''",
		"!!float abc", "!!float ''", "!!timestamp 2035-02-30", "!!timestamp nope",
	} {
		t.Run("rejects "+form, func(t *testing.T) {
			node, err := scalarNode(t, form)
			if err != nil {
				t.Fatalf("parse: %v", err)
			}
			if got, err := Resolve(node); err == nil {
				t.Errorf("accepted as %s %q; PyYAML raises", got.Kind.Tag(), got.String())
			}
		})
	}

	// Quoting alone still forces a string — only the TAG branch was wrong.
	for _, tc := range []struct{ form, want string }{
		{"'0'", "0"}, {`"2035-01-15"`, "2035-01-15"}, {"'true'", "true"},
	} {
		node, err := scalarNode(t, tc.form)
		if err != nil {
			t.Fatalf("parse %q: %v", tc.form, err)
		}
		got, err := Resolve(node)
		if err != nil {
			t.Fatalf("Resolve(%q): %v", tc.form, err)
		}
		if got.Kind != KindStr || got.Raw != tc.want {
			t.Errorf("%s resolved to %s %q, want !!str %q", tc.form, got.Kind.Tag(), got.Raw, tc.want)
		}
	}
}

// TestResolveRejectsNonScalar keeps the error path honest — internal packages
// return errors rather than exiting.
func TestResolveRejectsNonScalar(t *testing.T) {
	var doc yaml.Node
	if err := yaml.Unmarshal([]byte("k: [1, 2]\n"), &doc); err != nil {
		t.Fatalf("parse: %v", err)
	}
	if _, err := Resolve(doc.Content[0].Content[1]); err == nil {
		t.Error("want an error for a sequence node, got nil")
	}
	if _, err := Resolve(nil); err == nil {
		t.Error("want an error for a nil node, got nil")
	}
}
