package yamlio

import (
	"encoding/json"
	"os"
	"testing"

	"gopkg.in/yaml.v3"
)

// truthRow is one measured row of testdata/pyyaml-truth.json. That file is
// generated by loading a scalar corpus through the repo's vendored PyYAML
// 6.0.2 and through gopkg.in/yaml.v3 v3.0.1 and recording what each produced.
// Nothing in it is hand-written, so the expectations below are measurements
// rather than recollections.
type truthRow struct {
	Form   string `json:"form"`
	Expect string `json:"expect"`
	PyTag  string `json:"pyTag"`
	PyType string `json:"pyType"`
	PyStr  string `json:"pyStr"`
	GoTag  string `json:"goTag"`
	GoStr  string `json:"goStr"`
	// Diverges records that yaml.v3's own rendering differs from PyYAML's.
	// These are the rows that make this package necessary.
	Diverges bool `json:"diverges"`
}

func loadTruth(t *testing.T) []truthRow {
	t.Helper()
	blob, err := os.ReadFile("testdata/pyyaml-truth.json")
	if err != nil {
		t.Fatalf("read truth table: %v", err)
	}
	var rows []truthRow
	if err := json.Unmarshal(blob, &rows); err != nil {
		t.Fatalf("parse truth table: %v", err)
	}
	if len(rows) == 0 {
		t.Fatal("truth table is empty")
	}
	return rows
}

// scalarNode parses "k: <form>" and hands back the value node, which is how
// every scalar in the workspace actually reaches the resolver.
func scalarNode(t *testing.T, form string) (*yaml.Node, error) {
	t.Helper()
	src := form
	if form == "<EMPTY>" {
		src = ""
	}
	var doc yaml.Node
	if err := yaml.Unmarshal([]byte("k: "+src+"\n"), &doc); err != nil {
		return nil, err
	}
	return doc.Content[0].Content[1], nil
}

// TestResolveMatchesPyYAML asserts that for every measured form, the resolved
// kind matches PyYAML's tag and the rendering matches Python's str().
func TestResolveMatchesPyYAML(t *testing.T) {
	for _, row := range loadTruth(t) {
		t.Run(row.Form, func(t *testing.T) {
			node, err := scalarNode(t, row.Form)
			if row.Expect == "parse_error" {
				if err == nil {
					t.Fatalf("want a parse error (PyYAML: %s), got node %q", row.PyStr, node.Value)
				}
				return
			}
			if err != nil {
				t.Fatalf("parse %q: %v", row.Form, err)
			}

			got, err := Resolve(node)
			if row.Expect == "resolve_error" {
				if err == nil {
					t.Fatalf("want a resolve error (PyYAML: %s), got %q", row.PyStr, got.String())
				}
				return
			}
			if err != nil {
				t.Fatalf("Resolve(%q): %v", row.Form, err)
			}

			if got.Kind.Tag() != row.PyTag {
				t.Errorf("kind: got %s, PyYAML resolves %s", got.Kind.Tag(), row.PyTag)
			}
			// The merge and value tags resolve but have no Python value, so
			// only the tag is checked for them.
			if row.Expect == "construct_error" {
				return
			}
			if s := got.String(); s != row.PyStr {
				t.Errorf("render: got %q, PyYAML str() gives %q (yaml.v3 alone gives %q)",
					s, row.PyStr, row.GoStr)
			}
		})
	}
}

// TestDivergentFormsAreCovered guards the table itself: if a regeneration ever
// produced a corpus where nothing diverges, the suite above would pass while
// proving nothing.
func TestDivergentFormsAreCovered(t *testing.T) {
	rows := loadTruth(t)
	var divergent int
	for _, row := range rows {
		if row.Diverges {
			divergent++
		}
	}
	if divergent == 0 {
		t.Fatal("no divergent forms in the truth table; the table is not exercising the port risk")
	}
	t.Logf("%d of %d measured forms render differently under yaml.v3 alone", divergent, len(rows))
}

// TestQuotedAndUnquotedShareOnePath is R-1.6's named case: line 8 of the
// deviations fixture is unquoted and line 10 is quoted, and both must come out
// as the same rendered date string.
func TestQuotedAndUnquotedShareOnePath(t *testing.T) {
	const src = "reviewDate: 2035-01-15\nother: '2035-01-14'\n"
	var doc yaml.Node
	if err := yaml.Unmarshal([]byte(src), &doc); err != nil {
		t.Fatalf("parse: %v", err)
	}
	m := doc.Content[0]

	unquoted, err := Resolve(m.Content[1])
	if err != nil {
		t.Fatalf("unquoted: %v", err)
	}
	quoted, err := Resolve(m.Content[3])
	if err != nil {
		t.Fatalf("quoted: %v", err)
	}

	if unquoted.Kind != KindTimestamp {
		t.Errorf("unquoted kind: got %s, want !!timestamp", unquoted.Kind.Tag())
	}
	if quoted.Kind != KindStr {
		t.Errorf("quoted kind: got %s, want !!str", quoted.Kind.Tag())
	}
	if got := unquoted.String(); got != "2035-01-15" {
		t.Errorf("unquoted render: got %q, want %q", got, "2035-01-15")
	}
	if got := quoted.String(); got != "2035-01-14" {
		t.Errorf("quoted render: got %q, want %q", got, "2035-01-14")
	}
}

// TestGitCommitPinKeepsPrecision covers the divergence found in the committed
// fixtures: an unquoted all-digit 40-character commit SHA. PyYAML's int is
// arbitrary precision and renders every digit; yaml.v3 overflows int64, falls
// back to float64, and renders 1.1111111111111112e+39 — a silently corrupted
// git ref.
func TestGitCommitPinKeepsPrecision(t *testing.T) {
	const sha = "1111111111111111111111111111111111111111"
	var doc yaml.Node
	if err := yaml.Unmarshal([]byte("pin: {commit: "+sha+"}\n"), &doc); err != nil {
		t.Fatalf("parse: %v", err)
	}
	node := doc.Content[0].Content[1].Content[1]

	got, err := Resolve(node)
	if err != nil {
		t.Fatalf("Resolve: %v", err)
	}
	if got.Kind != KindInt {
		t.Fatalf("kind: got %s, want !!int", got.Kind.Tag())
	}
	if got.String() != sha {
		t.Errorf("render: got %q, want %q", got.String(), sha)
	}
}

// TestResolveRejectsNonScalar keeps the error path honest — internal packages
// return errors rather than exiting.
func TestResolveRejectsNonScalar(t *testing.T) {
	var doc yaml.Node
	if err := yaml.Unmarshal([]byte("k: [1, 2]\n"), &doc); err != nil {
		t.Fatalf("parse: %v", err)
	}
	if _, err := Resolve(doc.Content[0].Content[1]); err == nil {
		t.Error("want an error for a sequence node, got nil")
	}
	if _, err := Resolve(nil); err == nil {
		t.Error("want an error for a nil node, got nil")
	}
}
