package difftest

import (
	"context"
	"crypto/sha256"
	"encoding/hex"
	"fmt"
	"io"
	"io/fs"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"
)

// stepTimeout bounds a single CLI invocation. Generous: `workspace sync` clones
// over file:// and the banking fixtures are the largest in the corpus.
const stepTimeout = 180 * time.Second

// tsRe matches a generated UTC timestamp. Together with the workspace path
// these are the only two genuinely non-deterministic things the CLI emits.
var tsRe = regexp.MustCompile(`\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}Z`)

// normalizer returns a function replacing the non-deterministic values with
// stable placeholders: the temp workspace path (<WS>), the temp synthetic-
// fixture path (<SRC>), and a generated UTC timestamp (<TS>).
//
// <SRC> is required by the golden that <WS> alone was not. The Python harness
// this replaces ran both binaries inside ONE temp directory in ONE process, so
// the synthetic git source repo had the same absolute path on both sides and
// cancelled out of the comparison. A golden outlives the run, and
// `workspace sync` records the source `file://` URL in workspace.lock.yaml —
// so without this the lock hash moves every run and the suite fails at random.
//
// Otherwise deliberately minimal. Over-normalizing is how a characterization
// suite goes quietly blind: every substitution is a class of change it can no
// longer see. TODAY-derived dates are NOT normalized — they are deterministic
// within a run, and a golden carrying one is regenerated by the same command
// that would surface a date-handling change.
func normalizer(wsPath, srcBase string) func(string) string {
	type sub struct{ from, to string }
	var subs []sub
	add := func(p, placeholder string) {
		if p == "" {
			return
		}
		subs = append(subs, sub{p, placeholder})
		if real, err := filepath.EvalSymlinks(p); err == nil && real != p {
			subs = append(subs, sub{real, placeholder})
		}
	}
	add(wsPath, "<WS>")
	add(srcBase, "<SRC>")

	// Longest first, globally. On darwin /var/... is a symlink to
	// /private/var/..., so one path is a suffix of the other; replacing the
	// short one first would leave a "/private<WS>" fragment behind. The
	// workspace copy also lives under the fixture base for some invocations,
	// so the ordering has to be across both sets, not within each.
	sort.Slice(subs, func(i, j int) bool { return len(subs[i].from) > len(subs[j].from) })

	return func(text string) string {
		for _, s := range subs {
			text = strings.ReplaceAll(text, s.from, s.to)
		}
		return tsRe.ReplaceAllString(text, "<TS>")
	}
}

// entry is one path in a snapshotted tree.
type entry struct {
	Path   string
	Kind   string // "dir" | "file" | "link" | "unreadable"
	Mode   fs.FileMode
	Digest string // sha256 of normalized content; for links, the target
}

// stepResult is one executed step.
type stepResult struct {
	Argv   []string
	Exit   int
	Stdout string
	Stderr string
}

// result is everything one invocation produced.
type result struct {
	Steps []stepResult
	Tree  []entry
}

// copyTree copies src to dst preserving symlinks and permission bits.
func copyTree(src, dst string) error {
	return filepath.WalkDir(src, func(path string, d fs.DirEntry, err error) error {
		if err != nil {
			return err
		}
		rel, err := filepath.Rel(src, path)
		if err != nil {
			return err
		}
		target := filepath.Join(dst, rel)
		info, err := d.Info()
		if err != nil {
			return err
		}
		switch {
		case info.Mode()&os.ModeSymlink != 0:
			link, err := os.Readlink(path)
			if err != nil {
				return err
			}
			if err := os.MkdirAll(filepath.Dir(target), 0o755); err != nil {
				return err
			}
			return os.Symlink(link, target)
		case d.IsDir():
			// Force u+wx now: a 0555 synced slice would otherwise be a directory
			// we cannot write into while copying its children.
			return os.MkdirAll(target, info.Mode().Perm()|0o700)
		default:
			if err := os.MkdirAll(filepath.Dir(target), 0o755); err != nil {
				return err
			}
			in, err := os.Open(path)
			if err != nil {
				return err
			}
			defer in.Close()
			out, err := os.OpenFile(target, os.O_CREATE|os.O_WRONLY|os.O_TRUNC,
				info.Mode().Perm()|0o200)
			if err != nil {
				return err
			}
			if _, err := io.Copy(out, in); err != nil {
				out.Close()
				return err
			}
			if err := out.Close(); err != nil {
				return err
			}
			// Restore the recorded mode: the 0444 on a synced slice is the gate
			// [8/8] invariant, so the copy has to carry it even though we needed
			// it writable a moment ago.
			return os.Chmod(target, info.Mode().Perm())
		}
	})
}

// chmodWritable makes every path under root writable by the owner. Fixtures
// contain read-only materialized slices (0444/0555); without this the copy
// cannot be re-synced or torn down.
func chmodWritable(root string) error {
	return filepath.WalkDir(root, func(path string, d fs.DirEntry, err error) error {
		if err != nil {
			return err
		}
		info, err := d.Info()
		if err != nil {
			return nil // vanished mid-walk; nothing to relax
		}
		if info.Mode()&os.ModeSymlink != 0 {
			return nil
		}
		mode := info.Mode().Perm() | 0o200
		if d.IsDir() {
			mode |= 0o100
		}
		_ = os.Chmod(path, mode)
		return nil
	})
}

// snapshotTree records every path under root as kind + mode + content digest.
//
// Paths with a `.git` component are skipped: git's object store carries reflog
// timestamps and pack nondeterminism that no CLI produced, so including it
// would make the golden fail at random. Materialized slices are fully recorded,
// mode bits included.
func snapshotTree(root string, norm func(string) string) ([]entry, error) {
	var out []entry
	err := filepath.WalkDir(root, func(path string, d fs.DirEntry, err error) error {
		if err != nil {
			return err
		}
		rel, err := filepath.Rel(root, path)
		if err != nil {
			return err
		}
		if rel == "." {
			return nil
		}
		for _, part := range strings.Split(rel, string(filepath.Separator)) {
			if part == ".git" {
				if d.IsDir() {
					return filepath.SkipDir
				}
				return nil
			}
		}
		rel = filepath.ToSlash(rel)
		info, err := d.Info()
		if err != nil {
			return err
		}
		switch {
		case info.Mode()&os.ModeSymlink != 0:
			link, err := os.Readlink(path)
			if err != nil {
				return err
			}
			out = append(out, entry{Path: rel, Kind: "link", Digest: norm(link)})
		case d.IsDir():
			out = append(out, entry{Path: rel, Kind: "dir", Mode: info.Mode().Perm()})
		default:
			raw, err := os.ReadFile(path)
			if err != nil {
				out = append(out, entry{Path: rel, Kind: "unreadable",
					Mode: info.Mode().Perm(), Digest: err.Error()})
				return nil
			}
			payload := raw
			if utf8.Valid(raw) {
				payload = []byte(norm(string(raw)))
			}
			sum := sha256.Sum256(payload)
			out = append(out, entry{Path: rel, Kind: "file",
				Mode: info.Mode().Perm(), Digest: hex.EncodeToString(sum[:])})
		}
		return nil
	})
	if err != nil {
		return nil, err
	}
	sort.Slice(out, func(i, j int) bool { return out[i].Path < out[j].Path })
	return out, nil
}

// runInvocation copies the fixture, runs every step in that one copy, and
// snapshots the resulting tree.
func runInvocation(binary string, in Inv, fx *fixtureSet, workdir string) (*result, error) {
	ws := filepath.Join(workdir, "ws")
	if err := copyTree(fx.path(in.Fixture), ws); err != nil {
		return nil, fmt.Errorf("copying fixture %q: %w", in.Fixture, err)
	}
	if err := chmodWritable(ws); err != nil {
		return nil, err
	}
	norm := normalizer(ws, fx.base)

	env := []string{}
	for _, kv := range os.Environ() {
		if strings.HasPrefix(kv, "COMPANY_OS_WORKSPACE_ROOT=") {
			continue // the corpus addresses the workspace explicitly, via --root
		}
		env = append(env, kv)
	}
	env = append(env, "LC_ALL=C", "TERM=dumb", "COLUMNS=80")

	res := &result{}
	for _, step := range in.Steps {
		if len(step) == 1 && step[0] == tamperStep {
			res.Steps = append(res.Steps, stepResult{Argv: step, Exit: 0,
				Stderr: tamper(ws)})
			continue
		}
		argv := []string{}
		if !contains(step, "--root") {
			argv = append(argv, "--root", ws)
		}
		argv = append(argv, step...)

		ctx, cancel := context.WithTimeout(context.Background(), stepTimeout)
		cmd := exec.CommandContext(ctx, binary, argv...)
		cmd.Dir = ws
		cmd.Env = env
		cmd.Stdin = nil // no TTY, no input: `init` with no flags must exit 7
		var stdout, stderr strings.Builder
		cmd.Stdout = &stdout
		cmd.Stderr = &stderr
		runErr := cmd.Run()
		code := cmd.ProcessState.ExitCode()
		if ctx.Err() == context.DeadlineExceeded {
			cancel()
			return nil, fmt.Errorf("step %v timed out after %s", step, stepTimeout)
		}
		cancel()
		if code == -1 && runErr != nil {
			return nil, fmt.Errorf("step %v did not run: %w", step, runErr)
		}
		res.Steps = append(res.Steps, stepResult{
			Argv:   step,
			Exit:   code,
			Stdout: norm(stdout.String()),
			Stderr: norm(stderr.String()),
		})
	}

	tree, err := snapshotTree(ws, norm)
	if err != nil {
		return nil, err
	}
	res.Tree = tree
	return res, nil
}

// tamper performs the deterministic in-tree mutation that drives gate [8/8].
// Returns "" on success, or the reason it could not run — never silently
// no-ops, because a tamper that did not happen turns the next step's [FAIL]
// into a pass.
func tamper(ws string) string {
	target := filepath.Join(ws, "platforms", "testplat", "governance", "requirements.yaml")
	if _, err := os.Stat(target); err != nil {
		return fmt.Sprintf("tamper target absent: %v", err)
	}
	if err := os.Chmod(filepath.Dir(target), 0o755); err != nil {
		return fmt.Sprintf("tamper failed: %v", err)
	}
	if err := os.Chmod(target, 0o644); err != nil {
		return fmt.Sprintf("tamper failed: %v", err)
	}
	if err := os.WriteFile(target,
		[]byte("version: 1\nplatform: tampered\nrequirements: []\n"), 0o644); err != nil {
		return fmt.Sprintf("tamper failed: %v", err)
	}
	return ""
}

func contains(hay []string, needle string) bool {
	for _, s := range hay {
		if s == needle {
			return true
		}
	}
	return false
}

// render serializes a result into the golden text form.
//
// Byte counts are written alongside each stream so a trailing-newline change is
// visible in the diff rather than invisible, and so a stream whose content
// happens to contain a "---" line cannot be misread by someone reviewing it.
func render(in Inv, res *result) string {
	var b strings.Builder
	fmt.Fprintf(&b, "# id:      %s\n", in.ID)
	fmt.Fprintf(&b, "# fixture: %s\n", in.Fixture)
	fmt.Fprintf(&b, "# group:   %s\n", in.Group)
	if in.Note != "" {
		fmt.Fprintf(&b, "# note:    %s\n", in.Note)
	}
	if in.Unstable != "" {
		fmt.Fprintf(&b, "# unstable: %s\n", wrapComment(in.Unstable))
	}

	for i, s := range res.Steps {
		argv := strings.Join(s.Argv, " ")
		if argv == "" {
			argv = "(no args)"
		}
		fmt.Fprintf(&b, "\n=== step %d: %s\n", i+1, argv)
		fmt.Fprintf(&b, "exit %d\n", s.Exit)
		writeStream(&b, "stdout", s.Stdout, in.UnstableStream() == "stdout")
		writeStream(&b, "stderr", s.Stderr, in.UnstableStream() == "stderr")
	}

	fmt.Fprintf(&b, "\n=== tree (%d entries)\n", len(res.Tree))
	for _, e := range res.Tree {
		switch e.Kind {
		case "dir":
			fmt.Fprintf(&b, "d %04o %-64s %s\n", e.Mode, "", e.Path)
		case "link":
			fmt.Fprintf(&b, "l %4s %-64s %s -> %s\n", "", "", e.Path, e.Digest)
		case "unreadable":
			fmt.Fprintf(&b, "? %04o %-64s %s (%s)\n", e.Mode, "", e.Path, e.Digest)
		default:
			fmt.Fprintf(&b, "f %04o %-64s %s\n", e.Mode, e.Digest, e.Path)
		}
	}
	return b.String()
}

func writeStream(b *strings.Builder, name, content string, excluded bool) {
	if excluded {
		fmt.Fprintf(b, "--- %s EXCLUDED (non-deterministic under a single binary)\n", name)
		return
	}
	fmt.Fprintf(b, "--- %s (%d bytes)\n", name, len(content))
	if content != "" {
		b.WriteString(content)
		if !strings.HasSuffix(content, "\n") {
			b.WriteString("\n")
		}
	}
}

// wrapComment folds a long reason onto continuation lines so goldens stay
// readable at 80 columns.
func wrapComment(s string) string {
	const width = 68
	words := strings.Fields(s)
	var out strings.Builder
	col := 0
	for i, w := range words {
		if col > 0 && col+1+len(w) > width {
			out.WriteString("\n#           ")
			col = 0
		} else if i > 0 {
			out.WriteString(" ")
			col++
		}
		out.WriteString(w)
		col += len(w)
	}
	return out.String()
}
